/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_xgfjyw_libnettools_NetSelect */

#ifndef _Included_com_github_xgfjyw_libnettools_NetSelect
#define _Included_com_github_xgfjyw_libnettools_NetSelect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xgfjyw_libnettools_NetSelect
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_xgfjyw_libnettools_NetSelect_test(JNIEnv *, jobject, jstring, jint);

JNIEXPORT jstring JNICALL Java_com_github_xgfjyw_libnettools_NetSelect_randomString(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
